project_id = "dgxtxtcmyhbgpewmdcvc"

[functions.bootstrap-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.followup-reminders]
verify_jwt = false

[functions.purge-farmer]
verify_jwt = false

[functions.purge-user-by-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false
